# Generated by Django 4.2.8 on 2024-02-04 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_patientdischargedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdischargedetails',
            old_name='otherCharges',
            new_name='otherCharge',
        ),
    ]
