# Generated by Django 4.2.8 on 2024-02-04 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_rename_othercharges_patientdischargedetails_othercharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdischargedetails',
            name='releaseDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
